// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BZXsESn8S8Jnrv2Fvwi405vWwUwsz9c',
    appId: '1:609384542584:web:745c1610a440c67d0fd88d',
    messagingSenderId: '609384542584',
    projectId: 'depot-kayu-pos',
    authDomain: 'depot-kayu-pos.firebaseapp.com',
    storageBucket: 'depot-kayu-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2b9jA0-fo31rODPlo79TWuHHyQWfkgs',
    appId: '1:609384542584:android:2d5f8b3c65f11fa60fd88d',
    messagingSenderId: '609384542584',
    projectId: 'depot-kayu-pos',
    storageBucket: 'depot-kayu-pos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk8hBXTikQT1qLEz4aXBTa3ZsGA538n_o',
    appId: '1:609384542584:ios:ecfca2cf8230dbc30fd88d',
    messagingSenderId: '609384542584',
    projectId: 'depot-kayu-pos',
    storageBucket: 'depot-kayu-pos.firebasestorage.app',
    iosBundleId: 'com.example.depotKayuApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk8hBXTikQT1qLEz4aXBTa3ZsGA538n_o',
    appId: '1:609384542584:ios:ecfca2cf8230dbc30fd88d',
    messagingSenderId: '609384542584',
    projectId: 'depot-kayu-pos',
    storageBucket: 'depot-kayu-pos.firebasestorage.app',
    iosBundleId: 'com.example.depotKayuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BZXsESn8S8Jnrv2Fvwi405vWwUwsz9c',
    appId: '1:609384542584:web:f35d73a49e1037860fd88d',
    messagingSenderId: '609384542584',
    projectId: 'depot-kayu-pos',
    authDomain: 'depot-kayu-pos.firebaseapp.com',
    storageBucket: 'depot-kayu-pos.firebasestorage.app',
  );
}
